---
- hosts: all
  become: true

  vars:
    - anaconda_make_sys_default: True

  roles:
    - anaconda

  post_tasks:

    - name: import role
      import_role:
        name: anaconda 

    - name: Create jupyter notebook configuration directory
      file:
        path: /home/vagrant/.jupyter
        state: directory
        owner: vagrant
        group: vagrant

    - name: Install jupyter configuration file
      copy:
        src: files/jupyter_notebook_config.py
        dest: /home/vagrant/.jupyter
        owner: vagrant
        group: vagrant

    - name: Create jupyter notebook directory
      file:
        path: /home/vagrant/notebooks
        state: directory
        owner: vagrant
        group: vagrant

    - name: Install jupyter notebook initd service
      template:
        src: files/jupyter-notebook
        dest: /etc/init.d
        mode: 0755

    - name: Install package "g++"
      apt:
        name: g++
        state: present

    - name: Install package "git"
      apt:
        name: git
        state: present

    - name: Install package "swig"
      apt:
        name: swig
        state: present

    - name: Install package "libasound2-dev"
      apt:
        name: libasound2-dev
        state: present

    - name: Install package "fluidsynth"
      apt:
        name: fluidsynth
        state: latest

    - name: Install package "libjack-dev"
      apt:
        name: libjack-dev
        state: latest

    - name: Enable and start jupyter notebook service
      service:
        name: jupyter-notebook
        enabled: yes
        state: started

    - name: Update pip
      command: /usr/local/Anaconda3-5.1.0-Linux-x86_64/bin/pip install --upgrade pip
      args:
        chdir: /usr/local/Anaconda3-5.1.0-Linux-x86_64/bin/

    - name: Install python library through pip requirements
      pip:
        requirements: /home/vagrant/provision/requirements.txt
        executable: /usr/local/anaconda/bin/pip

    - name: install python library via conda
      conda: name={{ item }} state=latest executable="/usr/local/anaconda/bin/conda"
      with_items:
       - snuggs
